---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Slack Bot using AWS Lambda & Scala'

Parameters:
  BotToken:
    Type: String
    Description: "The Slack Bot Token"

Resources:
  MyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ScalaSlackLambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ScalaSlackLambda-lambda
      Code:
        ZipFile: |
          dummy value to be replaced by proper upload
      Handler: lambda.myJsHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          SLACK_BOT_TOKEN: !Ref BotToken
      Role: !GetAtt MyFunctionRole.Arn

  FunctionResourcePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref MyFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*'

  HttpApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: ScalaSlackLambda-http-api
      Description: An Amazon API Gateway HTTP API and an AWS Lambda function.
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - POST
      Target: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${MyFunction}/invocations

Outputs:
  HttpApiEndpoint:
    Description: The default endpoint for the HTTP API.
    Value: !GetAtt HttpApi.ApiEndpoint