# fly.toml app configuration file generated for scala-slack-bot on 2023-08-14T09:39:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scala-slack-bot"
primary_region = "ams"

[build]
image = "registry.fly.io/scala-slack-bot:latest"

[http_service]
  internal_port = 9876
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
