# https://fly.io/docs/reference/configuration/
app = "scala-slack-bot"
primary_region = "ams"

[build]
image = "registry.fly.io/scala-slack-bot:latest"

[http_service]
  internal_port = 9876
  force_https = true
  min_machines_running = 0